### ISSUE TITLE
Cannot render Radio Buttons

### ISSUE THREAD

**Issue by duymai1612** [kieutridang/achievement-book#19]
Here is my file: [https://github.com/kieutridang/achievement-book/blob/AB-011/client/components/SingleChoice/index.jsx](url)
When i `npm run start` there's no bug but the radio input and its label aren't rendered. I think the problem is in line 21-24 but i don't know what it is.

**Comment by DuyBui1993** [comment]
This was resolved by @duymai1612 and @zigonk.

Reason:
- This issue happen because he forgot to write the `return ( ... )` on the render() function.

@kieutridang Please help closing this issue.
